- name: HCP
  hosts: all
  tasks:
  - name: Execute a terraform plan
    hashicorp.terraform.run:
      organization: "TechXchangeNL"
      workspace: "{{ workspace }}"
      run_message: "Review infrastructure changes"
      # plan_only: true
      poll: true
      state: "present"
